[env:display_4_3_capacitive]
platform = espressif32
board = jc4827w543c
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/moononournation/Arduino_GFX.git#v1.4.6
    https://github.com/mmMicky/TouchLib.git
    lvgl/lvgl@^8.3.11
    bblanchon/ArduinoJson@^7.2.0
build_flags =
    -I include
    -I secrets
    -D TOUCH_MODULES_GT911
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -mfix-esp32-psram-cache-issue
