#!/usr/bin/env python3
"""Turn a phrase (or an existing WAV) into src/audio_test/speech_clip.h.

The audio test has no filesystem to read from, so the clip is compiled into the
image as a plain int16 array. Speech survives 16 kHz mono perfectly well, and at
that rate a second of audio costs ~32 KB of flash.

    tools/make_speech_clip.py --text "Reef panel online."
    tools/make_speech_clip.py --wav some_recording.wav

Needs espeak-ng (for --text), sox, and numpy.

The processing is aimed at one specific speaker: the ~20 mm cavity driver on P7,
1 W into 8 ohms. Raw espeak output through it is much quieter than it needs to
be, for two reasons that want different fixes -- see the chain below.
"""

import argparse
import array
import math
import pathlib
import shutil
import subprocess
import sys
import tempfile
import wave

import numpy as np

RATE = 16000
CEILING_DB = -1.0
DRIVE_DB = 16.0      # 6 dB of this just undoes the staging gain below;
                     # past ~18 dB the limiter works harder for very little extra
HIGHPASS_HZ = 200    # the cone cannot reproduce anything below this
PRESENCE_HZ = 3000   # where this driver is efficient and the ear is most sensitive
PRESENCE_DB = 4.0

HEADER = pathlib.Path(__file__).resolve().parent.parent / "src" / "audio_test" / "speech_clip.h"


def require(tool):
    if shutil.which(tool) is None:
        sys.exit(f"{tool} is not installed (try: sudo apt install -y {tool})")


def synthesize(text, out_path):
    require("espeak-ng")
    # -s 150 is a shade slower than the default, which reads more clearly on a
    # small cone than the default rate does.
    subprocess.run(
        ["espeak-ng", "-v", "en-us+m3", "-s", "150", "-p", "45", "-w", str(out_path), text],
        check=True,
    )


def condition(src, dst):
    """Resample to 16 kHz mono and shape it for the speaker.

    gain -6 first because the presence boost adds level and there has to be
    somewhere for it to go; the limiter below makes that headroom back.
    """
    require("sox")
    subprocess.run(
        ["sox", str(src), "-r", str(RATE), "-c", "1", "-b", "16", str(dst),
         "gain", "-6",
         "highpass", str(HIGHPASS_HZ),
         "equalizer", str(PRESENCE_HZ), "1.2q", str(PRESENCE_DB)],
        check=True,
    )


def limit(x, rate, ceiling, lookahead_ms=2.0, release_ms=60.0):
    """Look-ahead brick-wall limiter.

    A compressor with an ordinary envelope follower does almost nothing here:
    espeak's plosives are faster than any attack time worth using, so the peak
    slips through and normalising afterwards just puts everything back where it
    started. Looking ahead by 2 ms means the gain is already down before the
    transient arrives, which is what lets the clip be driven hard without the
    peaks clipping.
    """
    from numpy.lib.stride_tricks import sliding_window_view

    la = max(1, int(rate * lookahead_ms / 1000))
    padded = np.concatenate([np.abs(x), np.zeros(la)])
    window_peak = sliding_window_view(padded, la + 1).max(axis=1)[:len(x)]
    target = np.minimum(1.0, ceiling / np.maximum(window_peak, 1e-9))

    # Gain drops instantly and recovers slowly, so it does not pump per syllable.
    alpha = math.exp(-1.0 / (rate * release_ms / 1000))
    gain = np.empty_like(target)
    current = 1.0
    for i, want in enumerate(target):
        current = want if want < current else alpha * current + (1 - alpha) * want
        gain[i] = current

    delayed = np.concatenate([np.zeros(la), x])[:len(x)]
    return delayed * gain


def speech_rms_db(x, rate):
    """RMS over the parts that are actually speech.

    Whole-file RMS counts the pauses between sentences and reads several dB
    quieter than the clip sounds, which makes it useless for judging loudness.
    """
    n = int(rate * 0.02)
    frames = x[:len(x) // n * n].reshape(-1, n)
    frame_rms = np.sqrt((frames * frames).mean(axis=1))
    active = frame_rms > frame_rms.max() * 0.05
    value = math.sqrt(float((frames[active] ** 2).mean()))
    return 20 * math.log10(value) if value > 0 else -99.0


def emit_header(samples, rate, text, source_name):
    ints = np.clip(np.round(samples * 32767.0), -32768, 32767).astype(np.int16)
    lines = []
    for i in range(0, len(ints), 16):
        lines.append("    " + ", ".join(str(int(v)) for v in ints[i:i + 16]) + ",")

    source = f'espeak-ng: "{text}"' if text else f"converted from {source_name}"
    HEADER.write_text(
        "// Generated by tools/make_speech_clip.py -- do not edit by hand.\n"
        f"// Source: {source}\n"
        f"// {len(ints)} samples, {rate} Hz mono, {len(ints) / rate:.2f} s, "
        f"{len(ints) * 2 / 1024:.0f} KB of flash.\n"
        f"// Peak {20 * math.log10(float(np.abs(samples).max())):.1f} dBFS, "
        f"speech-active RMS {speech_rms_db(samples, rate):.1f} dBFS.\n"
        "#pragma once\n\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        f"static constexpr int kSpeechSampleRate = {rate};\n"
        f"static constexpr size_t kSpeechSampleCount = {len(ints)};\n\n"
        "static const int16_t kSpeechSamples[] = {\n"
        + "\n".join(lines)
        + "\n};\n"
    )
    return ints


def main():
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--text", help="phrase to synthesize with espeak-ng")
    group.add_argument("--wav", help="existing audio file to convert instead")
    parser.add_argument("--drive", type=float, default=DRIVE_DB,
                        help=f"dB of gain into the limiter (default {DRIVE_DB:g})")
    args = parser.parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        if args.text:
            raw = tmp / "raw.wav"
            synthesize(args.text, raw)
        else:
            raw = pathlib.Path(args.wav)
        conditioned = tmp / "clip.wav"
        condition(raw, conditioned)

        with wave.open(str(conditioned), "rb") as w:
            if w.getsampwidth() != 2 or w.getnchannels() != 1:
                sys.exit("expected 16-bit mono after conversion")
            rate = w.getframerate()
            samples = np.array(array.array("h", w.readframes(w.getnframes())),
                               dtype=np.float64) / 32768.0

        before = speech_rms_db(samples, rate)
        limited = limit(samples * (10 ** (args.drive / 20)), rate, 10 ** (CEILING_DB / 20))
        after = speech_rms_db(limited, rate)

        emit_header(limited, rate, args.text, raw.name)

    print(f"wrote {HEADER}")
    print(f"  {len(limited)} samples, {len(limited) / rate:.2f} s, {len(limited) * 2 / 1024:.0f} KB")
    print(f"  speech RMS {before:.1f} -> {after:.1f} dBFS ({after - before:+.1f} dB), "
          f"peak {20 * math.log10(float(np.abs(limited).max())):.1f} dBFS")


if __name__ == "__main__":
    main()
